# Bank Customer Classification
## Given a dataset consisiting of Bank Customer information, we are asked to build a classifier which will tell us if a customer will exit the bank or not.

In [1]:
import theano
import tensorflow
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

import os
print(os.listdir("../input"))

['.DS_Store', 'Churn_Modelling.csv']


# Data Preprocessing 

### In this dataset, we have to consider which of the factors may play a role in someone exiting a bank. To do that we must look at all  the column and infer whether it will matter in classifying a new customer or not.  The information about a customer is entailed in columns 0 through 12 (`EstimatedSalary`), while the output (whether the customer exited or not) is stored in the 13th row (`Exited`). 

In [2]:
#importing the dataset
dataset = pd.read_csv('../input/Churn_Modelling.csv')
dataset.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

For as much as we care, neither the `CustomerID`, nor the `Surname` should matter in classification. 
Therefore, we will use columns 3 (`CreditScore`) inclusive through the 12th column (`EstimatedSalary`).

In [3]:
dataset.columns

Index(['RowNumber', 'CustomerId', 'Surname', 'CreditScore', 'Geography',
       'Gender', 'Age', 'Tenure', 'Balance', 'NumOfProducts', 'HasCrCard',
       'IsActiveMember', 'EstimatedSalary', 'Exited'],
      dtype='object')

In [7]:
X = dataset.loc[:,'CreditScore':'EstimatedSalary'].values # Credit Score through Estimated Salary
y = dataset.loc[:, 'Exited'].values # Exited

In [9]:
# Encoding categorical (string based) data. Country: there are 3 options: France, Spain and Germany
# This will convert those strings into scalar values for analysis
print(X[:8,1], '... will now become: ')
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
label_X_country_encoder = LabelEncoder()
X[:,1] = label_X_country_encoder.fit_transform(X[:,1]) #The column of country
print(X[:8,1])

['France' 'Spain' 'France' 'France' 'Spain' 'Spain' 'France' 'Germany'] ... will now become: 
[0 2 0 0 2 2 0 1]


| Country |  -> | Country|
|------|      |------|  |------|    
|   Spain |   -> |0|
|   France | -> |1|
|   France | ->  |1|
|   Germany | -> |2|

In [10]:
# We will do the same thing for gender. this will be binary in this dataset
print(X[:6,2], '... will now become: ')
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
label_X_gender_encoder = LabelEncoder()
X[:,2] = label_X_gender_encoder.fit_transform(X[:,2])
print(X[:6,2])

['Female' 'Female' 'Female' 'Female' 'Female' 'Male'] ... will now become: 
[0 0 0 0 0 1]


The Problem here is that we are treating the countries as one variable with ordinal values (0 < 1 <  2). Therefore, one way to get rid of that problem is to split the countries into respective dimensions. that is,

| Country |  -> | Country|-> |Spain|France|Germany|
|------|      |------|  |------|    |------|    |------|
|   Spain |   -> |0| -> |1|0|0|
|   France | -> |1| -> |0|1|0|
|   France | ->  |1| -> |0|1|0|
|   Germany | -> |2| -> |0|0|1|

In [11]:
# Converting the string features into their own dimensions. Gender doesn't matter here because its binary
countryhotencoder = OneHotEncoder(categorical_features = [1]) # 1 is the country column
X = countryhotencoder.fit_transform(X).toarray()

Gender doesn't need to go through Encoding because it is binary

In [12]:
X[:,0:3]

array([[1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       ...,
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.]])

You can now see that the first three columns represent the three countries that constituted the "country" category. We can now observe that  we essentially only need two columns: a 0 on two countries means that the country has to be the one variable which wasn't included. This will save us from the problem of using too many dimensions

|Spain|France|Germany|-> |France|Germany|
 |------|    |------|    |------|     |------|     |------|
 |1|0|0|-> |0|0|
|0|1|0|-> |1|0|
|0|1|0|-> |1|0|
|0|0|1|-> |0|1|

In [13]:
X = X[:,1:] # Got rid of Spain as a dimension. It is still there through our inferences

In [30]:
# Splitting the dataset into the Training and Testing set.
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.2, random_state = 0)

Feature scaling is a method used to standardize the range of independent variables or features of data. It is basically scaling all the dimensions to be even so that one independent variable does not dominate another. For example, bank account balance ranges from millions to 0, whereas gender is either 0 or 1. If one of the features has a broad range of values, the distance will be governed by this particular feature. Therefore, the range of all features should be normalized so that each feature contributes approximately proportionately to the final distance.

In [31]:
# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [32]:
X_train

array([[-0.5698444 ,  1.74309049,  0.16958176, ...,  0.64259497,
        -1.03227043,  1.10643166],
       [ 1.75486502, -0.57369368, -2.30455945, ...,  0.64259497,
         0.9687384 , -0.74866447],
       [-0.5698444 , -0.57369368, -1.19119591, ...,  0.64259497,
        -1.03227043,  1.48533467],
       ...,
       [-0.5698444 , -0.57369368,  0.9015152 , ...,  0.64259497,
        -1.03227043,  1.41231994],
       [-0.5698444 ,  1.74309049, -0.62420521, ...,  0.64259497,
         0.9687384 ,  0.84432121],
       [ 1.75486502, -0.57369368, -0.28401079, ...,  0.64259497,
        -1.03227043,  0.32472465]])

## END OF PREPROCESSING

## Making the ANN

In [33]:
import keras # Test out Theano when time permits as well

In [34]:
from keras.models import Sequential
from keras.layers import Dense

In [35]:
# Initializing the ANN
classifier = Sequential()

A hurestic tip is that the amount of nodes (dimensions) in your hidden layer should be the average of your input and output layers, which means that since we have 11 dimensions (representing **Independent variables** Note: Countries still compose only  **one** dimension) and we are looking for a binary output, we calculate this to be $(11+1)\div 2 = 6 $.

#### The breakdown of the inputs for the first layer is as follows:

*activiation*: **relu** becasue we are in an input layer. uses the ReLu activation function for $\phi$

*input_dim*: **11** because we span 11 dimensions in our input layer. This is needed for the first added layer. The subsequent layers's input dimensions can be inferred using the previously added layer's output dimension. The next hidden layer will know what to expect.

*units*: **6** nodes (number of nodes in hidden layer). Can think of this as number of nodes are in the next layer.

*kernel_initializer*: **uniform**  the distribution with which we randomly initialize weights for the nodes in this layer. 



In [36]:
# This adds the input layer (by specifying input dimension) AND the first hidden layer (units)
classifier.add(Dense(activation = 'relu', input_dim = 11, units=6, kernel_initializer='uniform'))

### We are going to add another layer to this model because we want to implement Deep Learning, which is an artificial Neural network with many layers.
We will make our second hidden layer also have 6 nodes, just playing with the same arithmetic we used to determine the dimensions of the first hidden layer (average of your input and output layers) $(11+1)\div 2 = 6 $.

In [37]:
# Adding the second hidden layer
# Notice that we do not need to specify input dim. 
classifier.add(Dense(activation = 'relu', units=6, kernel_initializer='uniform')) 

### Adding the output layer
#### The breakdown of the inputs for the output layer is as follows:

*activiation*: **sigmoid** becasue we are in an output layer. uses the Sigmoid activation function for $\phi$. This is used instead of the ReLu function becasue it generates probabilities for the outcome. We want the probability that each customer leaves the bank.  

*units*: **1** nodes (number of nodes in output layer). This will be the probability that a customer leaves.

*kernel_initializer*: **uniform**  the distribution with which we randomly initialize weights for the nodes in this layer. 

In [38]:
# Adding the output layer
# Notice that we do not need to specify input dim. 
# we have an output of 1 node, which is the the desired dimensions of our output (stay with the bank or not)
# We use the sigmoid because we want probability outcomes
classifier.add(Dense(activation = 'sigmoid', units=1, kernel_initializer='uniform')) 


### If we want more than two categories, then we will need to change 

 1) the *units* parameter to match the desired category count (In this example category: "will customer leave or not")
 
 2) the *activation* field to **softmax**.  Basically a sigmoid function but applied to a dependent variable that has more than 2 categories.

## Compiling the Neural Network
Basically applying Stochastic Gradient descent on the whole Neural Network. We are Tuning the individual weights on each neuron.

#### The breakdown of the inputs for compiling is as follows:

*optimizer*: ** adam** The algorithm we want to use to find the optimal set of weights in the neural networks.  Adam is a very efficeint variation of Stochastic Gradient Descent.

*loss*: **binary_crossentropy** This is the loss function used within adam. This should be the logarthmic loss. If our dependent (output variable) is *Binary*, it is **binary_crossentropy**. If *Categorical*, then it is called **categorical_crossentropy**

*metrics*: **[accuracy]** The accuracy metrics which will be evaluated(minimized) by the model. Used as accuracy criteria to imporve model performance. 

*kernel_initializer*: **uniform**  the distribution with which we randomly initialize weights for the nodes in this layer. 

In [39]:
classifier.compile(optimizer='adam', loss = 'binary_crossentropy', metrics=['accuracy'])

## Fitting the Neural Network
This is where we will be fitting the ANN to our training set.

#### The breakdown of the inputs for compiling is as follows:

** X_train** The independent variable portion of the data which needs to be fitted with the model.

** Y_train** The output portion of the data which the model needs to produce after fitting.

*batch_size*:  How often we want to back-propogate the error values so that individual node weights can be adjusted. 

*nb_epochs*: The number of times we want to run the entire test data over again to tune the weights. This is like the fuel of the algorithm. 

In [40]:
classifier.fit(X_train, y_train, batch_size=10, epochs=100)

Epoch 1/100
8000/8000 [==============================] - 2s 227us/step - loss: 0.4821 - acc: 0.7951
Epoch 2/100
8000/8000 [==============================] - 2s 214us/step - loss: 0.4286 - acc: 0.7960
Epoch 3/100
8000/8000 [==============================] - 2s 206us/step - loss: 0.4226 - acc: 0.7965
Epoch 4/100
8000/8000 [==============================] - 2s 201us/step - loss: 0.4190 - acc: 0.8182
Epoch 5/100
8000/8000 [==============================] - 2s 202us/step - loss: 0.4163 - acc: 0.8261
Epoch 6/100
8000/8000 [==============================] - 2s 205us/step - loss: 0.4146 - acc: 0.8299
Epoch 7/100
8000/8000 [==============================] - 2s 207us/step - loss: 0.4128 - acc: 0.8300
Epoch 8/100
8000/8000 [==============================] - 2s 203us/step - loss: 0.4119 - acc: 0.8319
Epoch 9/100
8000/8000 [==============================] - 2s 202us/step - loss: 0.4107 - acc: 0.8320
Epoch 10/100
8000/8000 [==============================] - 2s 201us/step - loss: 0.4099 - acc: 0.8330

8000/8000 [==============================] - 2s 202us/step - loss: 0.4002 - acc: 0.8337
Epoch 83/100
8000/8000 [==============================] - 2s 201us/step - loss: 0.4003 - acc: 0.8331
Epoch 84/100
8000/8000 [==============================] - 2s 202us/step - loss: 0.4007 - acc: 0.8351
Epoch 85/100
8000/8000 [==============================] - 2s 202us/step - loss: 0.4004 - acc: 0.8352
Epoch 86/100
8000/8000 [==============================] - 2s 202us/step - loss: 0.4005 - acc: 0.8339
Epoch 87/100
8000/8000 [==============================] - 2s 201us/step - loss: 0.4008 - acc: 0.8347
Epoch 88/100
8000/8000 [==============================] - 2s 201us/step - loss: 0.4010 - acc: 0.8347
Epoch 89/100
8000/8000 [==============================] - 2s 202us/step - loss: 0.4006 - acc: 0.8349
Epoch 90/100
8000/8000 [==============================] - 2s 201us/step - loss: 0.4006 - acc: 0.8347
Epoch 91/100
8000/8000 [==============================] - 2s 202us/step - loss: 0.4004 - acc: 0.8347
Epo

The output network should converge to an accuracy near 84%
## Testing the ANN
### Predicting the Test set results

This shows the probability of a customer leaving given the testing data. Each row in X_test corresponds to a row in Y_test

In [41]:
y_pred = classifier.predict(X_test)
y_pred[:8]

array([[0.1702105 ],
       [0.3839274 ],
       [0.18821351],
       [0.05871017],
       [0.13299334],
       [0.8613797 ],
       [0.07265257],
       [0.08375332]], dtype=float32)

To use the confusion Matrix, we need to convert the probabilities that a customer will leave the bank into the form true or false. So we will use the cutoff value 0.5 to indicate whether they are likely to exit or not.

In [42]:
y_pred = (y_pred > 0.5)
y_pred[:8]

array([[False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False]])

### Making the Confusion Matrix

In [43]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[1546   49]
 [ 266  139]]


### Significance of the confusion matrix value:

The output should be close to the table below:

||Predicted: No |Predicted: Yes|
 |------| |------|   |------|  
 |Actual: No|1546|49|
|Actual: Yes|266|139|


This means that we should have about $(1546 + 139) = 1685$ correct classifications out of our total testing data size of $2000$.
This means that our accuracy for this trial was $1685 \div 2000 = 84.25\%$, which matches the classifier's prediction

In [44]:
print (((cm[0][0]+cm[1][1])*100)/(cm[0][0]+cm[1][1]+cm[0][1]+cm[1][0]), '% of testing data was classified correctly')

84.25 % of testing data was classified correctly


## Testing on a random new user

using the ANN model to predict if the customer with the following informations will leave the bank: 

* Geography: France
* Credit Score: 600
* Gender: Male
* Age: 40 years old
* Tenure: 3 years
* Balance: \$60000
* Number of Products: 2
* Does this customer have a credit card ? Yes
* Is this customer an Active Member: Yes
* Estimated Salary: $50000
* So should we say goodbye to that customer ?

In [79]:
new_user_x = np.array([[0.0,1, # France
              600, # Credit score
              0, # Male
              40, # years old
              3, # tenure
              60_000, # balance
              2, # Number of products
              1, # Credit Card
              1, # Active
              50_000 # Salary
             ]])

In [80]:
new_user_x_norm = sc.transform(new_user_x)

In [81]:
print(classifier.predict(new_user_x_norm)[0][0]*100,'% probability that customer will leave') 

19.046124815940857 % probability that customer will leave
